//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shamil_Zaripov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PointIssueId { get; set; }
        public Nullable<int> StatusOrderId { get; set; }
        public string Structer { get; set; }
        public Nullable<System.DateTime> DateDelivery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Users Users { get; set; }
    }
}
