//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shamil_Zaripov
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointIssue
    {
        public int PointIssueId { get; set; }
        public Nullable<int> PointIssueCode { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public string House { get; set; }
    }
}
